### ISSUE TITLE
How to run "WhatIsThat" on GPU?

### ISSUE THREAD

**Issue by Shawn1222** [microsoft/psi-samples#15]
I've installed and configured CUDA, also set the parameter "CpuOnlyMode" to false in the AzureKincetBodyTrackerConfiguration. I am wondering how to configure the "WhatIsThat" project in Visual Studio 2019 to make it run by my GPU. Can you provide some instructions?

**Comment by sandrist** [comment]
Closing this issue as it is being addressed over here: https://github.com/microsoft/psi/issues/186
